Project.PL/Areas/DashBoard/Controllers/FruitsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Project.DAL.Data;
using Project.DAL.Models;
using Project.PL.Areas.DashBoard.ViewModels.ProductFruitsVM;
using Project.PL.Helpers;
using Project.PL.Views.ViewModels;

namespace Project.PL.Areas.DashBoard.Controllers
{
    [Area("DashBoard")]
    public class FruitsController : Controller
    {
        private readonly ApplicationDbContext dbContext;
        private readonly IMapper mapper;

        public FruitsController(ApplicationDbContext dbContext, IMapper mapper)
        {
            this.dbContext = dbContext;
            this.mapper = mapper;
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ProductFruitsCreateVM VM)
        {
            if (!ModelState.IsValid)
            {
                return View(VM);
            }
            VM.ImagName = FilesSetting.UploadFile(VM.Image, "Images");
            var model = mapper.Map<ProductFruit>(VM);
            dbContext.Add(model);
            dbContext.SaveChanges();
            return Content("Add Succeded");
        }
        [HttpGet]
        public IActionResult Display()
        {
            var product = dbContext.ProductFruits.ToList();
            var vm = mapper.Map<IEnumerable<ProductFruitDisplayVM>>(product);
            return View(vm);
        }
        [HttpGet]
        public IActionResult Delete(int Id)
        {
            var product = dbContext.ProductFruits.Find(Id);
            if(product is null)
            {
                return RedirectToAction(nameof(Display));
            }
            var vm = mapper.Map<ProductFruitsDeleteVM>(product);
            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletedConfirmed(int Id)
        {
            var product = dbContext.ProductFruits.Find(Id);
            if (product is null)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                FilesSetting.DeleteFile(product.ImagName, "Images");
                dbContext.Remove(product);
                dbContext.SaveChanges();
                return RedirectToAction(nameof(Display));
            }

        }
        public IActionResult Edit(int Id)
        {
            var product = dbContext.ProductFruits.Find(Id);
            if (product is null)
            {
                return NotFound();
            }
            else
            {

                return View(mapper.Map<ProductFruitsEditVM>(product));
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ProductFruitsEditVM vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }
            vm.ImagName = FilesSetting.UploadFile(vm.Image, "Images");
            var product = dbContext.ProductFruits.Find(vm.Id);
           
            if (product is null)
            {
                return NotFound();
            }
            else
            {
                FilesSetting.DeleteFile(product.ImagName, "Images");
                mapper.Map(vm, product);
                dbContext.SaveChanges();
                return RedirectToAction(nameof(Display));
            }

        }
    }
}

Project.PL/Areas/DashBoard/Views/Fruits/Create.cshtml
@model ProductFruitsCreateVM
@section MainHeader {
    Create Fruits Products
}
<div class="col-md-12">
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title"> Create </h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form asp-controller="Fruits" asp-action="Create" enctype="multipart/form-data">
            <div class="card-body">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" placeholder="Enter Name Services">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description"></label>
                    <input asp-for="Description" class="form-control" placeholder="Enter Name Description">
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price"></label>
                    <input asp-for="Price" class="form-control" placeholder="Enter Name Description">
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Image"></label>
                    <input asp-for="Image" class="form-control" placeholder="Enter Name Description">
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>


            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </form>
    </div>
</div>
<!-- /.card -->

Project.PL/Areas/DashBoard/Views/Fruits/Delete.cshtml
@model ProductFruitsDeleteVM
@section MainHeader{
    Delete
}
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title"> Delete </h3>
        </div>
        <div class="card-body">
            <p class="footer danger">Are you Sure to Delete @Model.Name</p>
        </div>
        <div class="card-footer">
            <form asp-controller="Fruits" asp-action="DeletedConfirmed">
                <input type="hidden" asp-for="Id" />
                <input type="submit" class="btn btn-danger" value="Delete" />
                <a class="btn btn-secondary" asp-controller="Fruits" asp-action="Display">Cancel</a>
            </form>
        </div>
    </div>
</div>

Project.PL/Areas/DashBoard/Views/Fruits/Display.cshtml
@model IEnumerable<ProductFruitDisplayVM>
@section MainHeader{
    Display Fruits Products
}
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title"> All Products Fruits</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table class="table table-bordered">
                <thead>
                    <tr>

                        <th>Name</th>
                        <th>Price</th>
                        <th>Description</th>
                        <th>Operation</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.Price</td>
                            <td>@item.Description</td>
                            <td>
                                <a class="btn btn-warning" asp-route-Id=@item.Id asp-action="Details" asp-controller="Fruits">Details</a>
                               <a class="btn btn-danger" asp-route-Id=@item.Id asp-action="Delete" asp-controller="Fruits">Delete</a>
                                <a class="btn btn-info" asp-route-Id=@item.Id asp-action="Edit" asp-controller="Fruits">Edit</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
        <div class="card-footer clearfix">
            <ul class="pagination pagination-sm m-0 float-right">
                <li class="page-item"><a class="page-link" href="#">«</a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">»</a></li>
            </ul>
        </div>
    </div>
    <!-- /.card -->
</div>

Project.PL/Areas/DashBoard/Views/Fruits/Edit.cshtml
@model ProductFruitsEditVM
@section MainHeader {
    Edit ProductFruits
}
<div class="col-md-12">
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title"> Edit </h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form asp-controller="Fruits" asp-action="Edit" enctype="multipart/form-data">
            <div class="card-body">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control"/>
                </div>
                <div class="form-group">
                    <label asp-for="Price"></label>
                    <input asp-for="Price"/>
                </div>
                <div class="form-group">
                    <label asp-for="Image"></label>
                    <input asp-for="Image"/>
                </div>

                <input type="hidden" asp-for="Id" class="form-control" placeholder="Enter Name Services">


            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </form>
    </div>
</div>
<!-- /.card -->